name: 'Terraform-Deploy'

on:
  push:
    branches:
    - main
  pull_request:

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: prod
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Instalando Terraform CLI
      uses: hashicorp/setup-terraform@v1
      
    - name: Terraform Init
      working-directory: ./terraform
      run: terraform init -var "do_token=${{ secrets.DO_PAT }}" -backend-config="access_key=${{ secrets.DO_SPACES_KEY }}" -backend-config="secret_key=${{ secrets.DO_SPACES_SECRET }}" -backend-config="bucket=${{ secrets.DO_SPACE_NAME }}"
    
    - name: Terraform Validate
      working-directory: ./terraform
      run: terraform validate
      
    - name: Terraform Plan
      working-directory: ./terraform
      run: terraform plan -input=false -var "do_token=${{ secrets.DO_PAT }}"
      
    - name: Terraform Apply
      working-directory: ./terraform
      run: terraform apply -var "do_token=${{ secrets.DO_PAT }}" -auto-approve -input=false
